### ISSUE TITLE
format własnej playlisty

### ISSUE THREAD

**Issue by memek-op** [en0x/script.etvguide#10]
Witam ponownie :)

jaki format powinna mieć własna playlista żeby przypisywanie streamów działało prawidłowo?

mam własną w formacie jak niżej i chciałbym, żeby etv guide przypisywał streamy z listy jeśli jest dany kanał - o ile to tak ma działać :)
#EXTINF:0,TLC
http://xxxx/playlist.m3u8 
#EXTINF:0,TVN 24
http://cccc/playlist.m3u8
#EXTINF:0,TVN METEO ACTIVE
http://bbbb/playlist.m3u8
itd...

**Comment by en0x** [comment]
Witam,
nie wiem dokladnie czy tak to ma wygladac ale podam ci przyklad z listy mojefilmy ktora dziala bez problemu we wtyczce.


`
#EXTM3U


#EXTINF:-1 tvg-id="" audio-track="pol" group-title="Film" tvg-logo="VOD%20Film.png",VOD Film
http://fsfsfs/channel.vod

#EXTINF:-1 tvg-id="" audio-track="pol" group-title="Film" tvg-logo="13%20Ulica%20FHD.png",13 Ulica FHD
http://fsdfsdfs/channel.m3u8

#EXTINF:-1 tvg-id="" audio-track="pol" group-title="Film" tvg-logo="MGM%20HD.png",AMC HD
http://sdfsffs/1576/channel.m3u8
`

**Comment by memek-op** [comment]
niestety nie działa... wskazuję w ustawieniach na plik i priorytet przypisywania b.wysoki.

ani jeden sposób ani drugi nie działa:
`#EXTINF:-1 tvg-id="" audio-track="pol" group-title="Film" tvg-logo="VOD%20Film.png",TVP 3 Katowice
http://195.245.213.230/live/katowice.isml/katowice.m3u8

#EXTINF:0,TVP 3 Katowice
http://195.245.213.230/live/katowice.isml/katowice.m3u8`

**Comment by pawel-yesware** [comment]
witaj!

```
#EXTM3U

#EXTINF:-1 tvg-id="TVP 3 Katowice"
http://195.245.213.230/live/katowice.isml/katowice.m3u8
```

powinno dzialac ;)

**Comment by memek-op** [comment]
potwierdzam działa :) dodam, że dokładne nazwy stacji do podstawienia w pliku m3u można wyciągnąć z bazy source.db programem DB Browser for SQLite. może komuś się przyda
