### ISSUE TITLE
linki CONST

### ISSUE THREAD

**Issue by memek-op** [en0x/script.etvguide#11]
a jednak jest problem.  Dla eski, wawy itp. przypisuje się stream na stałe i jest on nawet przed własną listą ustawioną z prio b.wysoki. W logach streamy  widnieją jako CONST. Wszystko jest OK kiedy są poprawne, ale Eska pozmieniała adresy i KODI się zapętla na Esce, a na pozostałych po 8 próbie połączenia przechodzi do streama z mojej playlisty. Logi:
18:11:34 T:1442890672  NOTICE: ETVGUIDE @ TelewizjaDaUpdater [UPD]     ESKA BEST MUSIC                CONST           http://stream.smcloud.net/live2/best/best_480p/playlist.m3u8
18:11:34 T:1442890672  NOTICE: ETVGUIDE @ TelewizjaDaUpdater [UPD]     ESKA GO                        CONST           http://stream.smcloud.net/live2/eska_party/eska_party_360p/playlist.m3u8
18:11:34 T:1442890672  NOTICE: ETVGUIDE @ TelewizjaDaUpdater [UPD]     VOX MUSIC TV                   CONST           rtmp://stream.smcloud.net/live/vox2/stream1
18:11:34 T:1442890672  NOTICE: ETVGUIDE @ TelewizjaDaUpdater [UPD]     WAWA TV                        CONST           http://stream.smcloud.net/live2/wawa/wawa_360p/playlist.m3u8
18:11:34 T:1442890672  NOTICE: ETVGUIDE @ TelewizjaDaUpdater [UPD]     CZWORKA POLSKIE RADIO          CONST           rtmp://stream85.polskieradio.pl/video/czworka.sdp
18:11:34 T:1442890672  NOTICE: ETVGUIDE @ TelewizjaDaUpdater [UPD]     STARS TV                       CONST           http://starstv.live.e55-po.insyscd.net/starstvhd.smil/chunklist_b1100000.m3u8?=key live=true
18:11:34 T:1442890672  NOTICE: ETVGUIDE @ TelewizjaDaUpdater [UPD]     Eska TV                        CONST           rtmp://stream.smcloud.net/live2/eskatv/eskatv_360p

18:14:00 T:1468056496  NOTICE: ETVGUIDE @ getStreamUrlList channel: ESKA BEST MUSIC     , stream: http://stream.smcloud.net/live2/best/best_480p/playlist.m3u8
18:14:00 T:1468056496  NOTICE: Previous line repeats 7 times.
18:14:00 T:1468056496  NOTICE: ETVGUIDE @ getStreamUrlList channel: ESKA BEST MUSIC     , stream: service=playlist&cid=57
18:14:00 T:1468056496  NOTICE: ETVGUIDE @ getStreamUrlList channel: ESKA BEST MUSIC     , stream: http://stream.smcloud.net/live2/best/best_480p/playlist.m3u8

na początku działało usunięcie streama (klawisz C) i uruchomienie ponowne wtyczki ale po czasie znów błędne linki CONST zastąpiły poprawne z listy

**Comment by en0x** [comment]
to pewnie daltego ze mam powpisywane streamy do eski w pliku mapy... jakbys mi dal nowe to bym je uaktualnil.

dzieki

**Comment by memek-op** [comment]
http://stream.smcloud.net/tv/eskatv/eskatv_360p/playlist.m3u8
http://stream.smcloud.net/tv/eskatv/eskatv_480p/playlist.m3u8

http://stream.smcloud.net/tv/best/best_360p/playlist.m3u8
http://stream.smcloud.net/tv/best/best_480p/playlist.m3u8

http://stream.smcloud.net/tv/eska_party/eska_party_360p/playlist.m3u8

http://stream.smcloud.net/tv/wawa/wawa_360p/playlist.m3u8
http://stream.smcloud.net/tv/wawa/wawa_480p/playlist.m3u8

http://stream.smcloud.net/live/hiphoptv/playlist.m3u8

**Comment by en0x** [comment]
Dzieki jak bede mial chwile to dodam,

a co do pierwszej.tv to zeby ogladac przez wtyczke musisz miec premium a przez przegladarke nie trzeba.... tak zrobili

**Comment by memek-op** [comment]
dzięki, pozdrawiam
