### ISSUE TITLE
problem z zamykaniem kanałów

### ISSUE THREAD

**Issue by MarniC00** [en0x/script.etvguide#15]
Witam,
Dziś zauważyłem następujący problem - przy próbie zatrzymania odtwarzania dowolnego kanału (mam konfigurację pod moje-filmy.tk) wtyczka jakby na chwilę zawieszała się i potem kanał odtwarzany jest na nowo. Czasem na sekundę pojawia się okno główne EPG ale potem znów włącza się kanał. Generalnie nie można zatrzymać odtwarzania bez całkowitego zamknięcia wtyczki. Do tej pory taki problem się nie pojawiał.

**Comment by en0x** [comment]
Witam jako tymczasowe rozwiazanie odznacz opcje
"Reconnect broken streams" albo po polsku "Polacz ponownie w przypadku rozlaczenia"
 we wtyczce 
powinno pomoc
