### ISSUE TITLE
E-tvguide Przestał działać :(

### ISSUE THREAD

**Issue by marekodfiranek** [en0x/script.etvguide#25]
Witam,
E-tvguide przestał działać dostaję komunikat : TWOJE USTAWIENIA LUB PODANY ADRES SĄ BŁĘDNE..
Czy E-tvguide powróci :?

**Comment by en0x** [comment]
Juz powinno byc naprawione

**Comment by marekodfiranek** [comment]
Dzieki Wielkie. Kawał solidnej roboty !!
