### ISSUE TITLE
wizja.tv kanaly

### ISSUE THREAD

**Issue by made8212** [en0x/script.etvguide#29]
apka nie pokazuje wszystkich kanalow wizja.tv np. tvnstyle badz canal+film

**Comment by en0x** [comment]
Niestety nie mam konta premium na wizja.tv i nie moge sprawdzic problemu. 

Jakbys mogl udostepnic konta na pare godzin to mozemy sprawdzic dlaczego kanaly nie sa przypisywane.

Jak cos to wal emaila na pawelkilian@gmail.com

**Comment by made8212** [comment]
wyslane :)

**Comment by en0x** [comment]
Dzieki wielkie.. Odpisalem ci na emaila...
Ticketa zamykam
