### ISSUE TITLE
yoy.tv  nie loguje się na konto

### ISSUE THREAD

**Issue by memek-op** [en0x/script.etvguide#30]
Witam,

mam premium w yoy.tv. Przez wtyczkę mrknowtv wszystko działa prawidłowo, natomiast w etv-guide dostaję komunikat, że nie mam premium. Żaden kanał nie chodzi.
kilka ostatnich linijek logów.
 times.
21:53:08 T:1102050224  NOTICE: Debug @ onClick
21:53:08 T:1102050224  NOTICE: ETVGUIDE @ playChannel2
21:53:08 T:1102050224  NOTICE: Debug @ RecordService isProgramRecorded program: Rozwód (3)
21:53:08 T:1102050224  NOTICE: Debug @ getListOfFilenamesForProgram
21:53:08 T:1840247728  NOTICE: ETVGUIDE @ Database.eventLoop() >>>>>>>>>> processing command: _getCustomStreamUrlList
21:53:08 T:1102050224  NOTICE: ETVGUIDE @ getStreamUrlList channel: HBO                 , stream: service=YoyTV&cid=775
21:53:08 T:1102050224  NOTICE: Debug @ Pla __init__ <gui.Pla object at 0x5adb9de0>
21:53:08 T:1425200048  NOTICE: ETVGUIDE @ PlayService parseUrl: cid 775, service YoyTV
21:53:08 T:1102050224  NOTICE: Debug @ onActionEPGMode keyId 7, buttonCode 0
21:53:09 T:1425200048  NOTICE: ETVGUIDE @ LoadVideoLink ERROR channelInfo is None! service: YoyTV
21:53:09 T:1425200048  NOTICE: ETVGUIDE @ PlayService _playUrlList detected faulty stream! playbackStopped: False, playStarted: False
21:53:09 T:1047704496  NOTICE: Debug @ Pla waitForPlayBackStopped not waiting anymore <gui.Pla object at 0x5adb9de0>
21:53:09 T:1047704496  NOTICE: Debug @ Pla onPlayBackStopped <gui.Pla object at 0x5adb9de0>

Pozdrawiam

**Comment by en0x** [comment]
```PlayService _playUrlList detected faulty stream! ```

znaczy ze sstream jest nie dobry..  niestety nie mam konta premium na yoy to nie mam jak sprawdzic... ale po zalogowaniu sie na darmowe konto i wlaczeniu tvn dla przykladu dziala bez problemu chwile a potem mi pokazuje ze nie mam premium to nie moge ogladac

**Comment by memek-op** [comment]
na pewno coś jest nie tak. ja właśnie wczoraj kupiłem premium an 15 dni dla testów i w czasie, kiedy (tak wnioskuję) był największy ruch to w etv-guide mi nie działało yoy tv, a we wtyczce MrKnowTV działało wszystko OK. Dodatkowym symptomem jest to, że w prawym dolnym rogu pojawia się komunikat o braku premium w serwisie yoy.tv.

**Comment by en0x** [comment]
Probowales moze wtyczke mtvguide? to samo sie dzieje?

**Comment by gumball1** [comment]
en0x z ciebie to zwykla KURWA jest , nie potrafisz nic ogarnac tylko czekasz na drapane co chlopaki z mods-kodi.pl wypuszcza. SZMACIARZ jestes !

**Comment by memek-op** [comment]
niestety nie mam premium na kods-kodi,  nie potrafię m-TVGuide uruchomić bez premium

**Comment by en0x** [comment]
@memek-op sciagnij najnowsza mtvguide i zobacz... w ustawienia epg wpisz moj url i zobacz.... http://epg.feenk.net/epg/epg.xml

**Comment by oldnorda** [comment]
witam
mam ten sam problem co przedmowca. Przez przegladarke i wtyczke know sie loguje na yoy.tv bez problemu. Jednak przez etvguide pokazuje blad logowania

**Comment by en0x** [comment]
Jutro powinna byc aktualizacja wtyczki

**Comment by en0x** [comment]
Aktualizacja 3.2.0 jest wydana.

**Comment by oldnorda** [comment]
Swietnie! dzieki. Zabieram sie za testy :)

**Comment by oldnorda** [comment]
Szukalem i nie moge znalesc wersi 3.2 a z poziomu kodi klikajac aktualizacje takze polazujke stara wersje.3.1 ktora juz posiadam.

**Comment by en0x** [comment]
Wejdz w ustawienia wtyczki i na ostatniej zakladce jest aktualizacja i tam wcisnij sprawdz.. powinno zaaktualizowac

**Comment by oldnorda** [comment]
Poszlo, dziekowac !

**Comment by en0x** [comment]
nic nie slyszalem w przeciagu ostatniego dnia odnosnie yoy to zamykam te zgloszenie
