### ISSUE TITLE
Problem z guide

### ISSUE THREAD

**Issue by borys76** [en0x/script.etvguide#4]
Jakis problem dzisiaj? Nieladuje guide caly dzien

**Comment by en0x** [comment]
Na jakim sprzecie?

Wiem ze na linuxie,maku i windowsie sie laduje bez problemu.

Na moim firetv sie nie laduje i pokazuje blad.

**Comment by borys76** [comment]
na android tv box kodi 15.2 i 16 to samo nie laduje guide

**Comment by en0x** [comment]
Patrze co sie moglo zmienic w generowaniu epg. bo tylko na androidach nie dziala od wczoraj chyba

**Comment by en0x** [comment]
Masz moze inne epg co dziala zebym mogl porownac?

**Comment by borys76** [comment]
dokladnie do wczoraj dzialalo super
mam nadzieje ze cos wykombinujesz
dzienki

2016-03-13 9:36 GMT-04:00 Pawel Kilian <notifications@github.com>:

**Comment by borys76** [comment]
mam dwa epg twoje i iamepg  oba przestaly dzialac  wczoraj wtym samym czasie

**Comment by en0x** [comment]
na mTVGuide moje epg i epg z epg.iptvlive.org tez nie dziala jak i u mnie...
ja tam zbytnio nic nie widze co by sie moglo w epg zmienic a czemu nie dziala to ciezkie pytanie

no nic bede patrzyl

**Comment by borys76** [comment]
Twoje epg zaczelo dzialac :)

**Comment by borys76** [comment]
Znowu padlo

**Comment by en0x** [comment]
wlasnie generuje nowe EPG z lekkimi poprawkami w konfiguracji... moze cos to da.... jak skonczy to dam znac... nowe EPG sie przewaznie generuje ~2godziny lol

**Comment by en0x** [comment]
Dzisiejsza wersja juz dziala na androidzie... i niech juz tak zostanie :)

Daj znac jak bedziesz mial jakies problemy

**Comment by borys76** [comment]
Dziala 
Dziekuje
