### ISSUE TITLE
Czy będzie jakaś aktualizacja?

### ISSUE THREAD

**Issue by marekodfiranek** [en0x/script.etvguide#40]
hey,
Czy szykuje się jakaś aktualizacja?
Może można poprawić pobieranie źródeł z tele-wizja?
Pozdrawiam

**Comment by en0x** [comment]
Witam aktualizacji juz raczej nie bedzie. ALe za to mozesz dalej uzywac mojego epg ktore przystosowalem pod mtvguide z mods-kodi.pl


http://epg.feenk.net/epg/epg.xml.zip

**Comment by marekodfiranek** [comment]
Program http://epg.feenk.net/epg/epg.xml.zip przestał działać. Czy serwer padł?

**Comment by en0x** [comment]
EPG powinno juz dzialac.
