### ISSUE TITLE
Problem z działaniem wtyczki

### ISSUE THREAD

**Issue by km4lin** [en0x/script.etvguide#43]
Od wczoraj mam problem z działaniem wtyczki. Najpierw pojawia się komunikat: 
'Obliczanie pozostałego czasu...'
Trwa to dłuższy czas a następnie pojawia się komunikat:
'Przepraszamy, wystąpił błąd!
Twoje ustawienia lub podany adres są błędne!
Sprawdź ustawienia albo spróbuj ponownie później
Obecnie wpisany link do EPG to: 1'
Byłbym bardzo wdzięczny za pomoc w uruchomieniu wtyczki, gdyż jest w moim przekonaniu lepsza niż m-TVGuide.
Pozdrawiam.

**Comment by en0x** [comment]
TO zostalo  naprawione z tydzien temu. sorki za nie dzialanie
