### ISSUE TITLE
Pytanie o EPG

### ISSUE THREAD

**Issue by kokosz887** [en0x/script.etvguide#44]
Witam serdecznie.

Nie wiem jak to jest z kolegi en0x EPG (wiem, że wtyczka nie jest rozwijana, ale samo EPG działa, więc pytam), ale chciałbym się dowiedzieć, czy jest możliwość aby dodać do EPG poniższe kanały:

-Water Planet
-Nowa TV
-Polsat Sport Fight
-Metro TV
-8 TV
-Polsat Music (dawniej Muzo TV)

Wszystkie te kanały są dostępne na stronie: http://programtv.interia.pl

Jeśli byłaby taka możliwość, to byłoby super.

Pozdrawiam i proszę o odpowiedź :)

**Comment by en0x** [comment]
Witam,
Kanaly zostana dodane w przeciagu paru dni

**Comment by kokosz887** [comment]
Dziękuję bardzo :) A te kanały pojawią się za jakiś czas? Bo sprawdzałem przed chwilą i w pliku xml nie widzę tych kanałów.

Pozdrawiam.

**Comment by en0x** [comment]
beda jutro, milego

**Comment by kokosz887** [comment]
Aha. Jeszcze raz bardzo dziękuję :D
