### ISSUE TITLE
EPG

### ISSUE THREAD

**Issue by kokosz887** [en0x/script.etvguide#45]
Dzień dobry.

Pańskie EPG przestało działać. Czy będzie Pan je jeszcze generował, czy niestety projekt upadł?

Pozdrawiam :)

**Comment by en0x** [comment]
Witam, Epg zostalo naprawione. Dzieki!

**Comment by kokosz887** [comment]
Super :D Bardzo dziękuję :)

A mam jeszcze pytanie. Czy byłaby możliwość dodania do EPG kanału Eska TV Extra?

Pozdrawiam :)

**Comment by en0x** [comment]
Witam, Sorki za pozna odpowiedz ale kanal zostal dodany powinien sie pojawic dzisiaj pozniej albo jutro rano
