### ISSUE TITLE
Eleven

### ISSUE THREAD

**Issue by kamilinho1** [en0x/script.etvguide#46]
Kanały Eleven zmieniły nazwę. Nazywają się teraz Eleven Sports 1, Eleven Sports 2 i Eleven Sports 3. Czy można to poprawić w EPG?

**Comment by kamilinho1** [comment]
I oczywiście loga tych kanałów.

**Comment by en0x** [comment]
Witam, Kanaly zostaly zmienione i powinny sie pojawic za pare godzin w epg
