### ISSUE TITLE
Pytanie o EPG

### ISSUE THREAD

**Issue by kokosz887** [en0x/script.etvguide#48]
Dzień dobry.

Pańskie EPG przestało działać (było wygenerowane do 21.05.2018). Czy będzie Pan je jeszcze generował, czy niestety projekt upadł?

Pozdrawiam :)

**Comment by en0x** [comment]
Witam, juz powinno dzialac od wczoraj. Problemy z serwerem ;)

**Comment by kokosz887** [comment]
Dziękuję bardzo. Pańskie EPG jest najlepsze w całym internecie :)

Pozdrawiam.

**Comment by kashkash18** [comment]
Witam , epg przestało działać . Mizna coś na to poradzić ??

**Comment by en0x** [comment]
Witam juz powinno byc naprawione
